#!/usr/bin/env bash
# Create all 6 Ductly WhatsApp Content Templates in Twilio + submit for Meta approval.
# Run this the moment the WhatsApp sender flips to Connected.
#
# Requires:
#   export TWILIO_ACCOUNT_SID=ACxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
#   export TWILIO_AUTH_TOKEN=<your-auth-token>
#
# Usage:  bash scripts/twilio/create-templates.sh
#
# Output: writes Content SIDs to scripts/twilio/content-sids.env — copy
# those into prod .env.local + n8n environment after run.

set -euo pipefail

: "${TWILIO_ACCOUNT_SID:?Set TWILIO_ACCOUNT_SID in your shell}"
: "${TWILIO_AUTH_TOKEN:?Set TWILIO_AUTH_TOKEN in your shell}"

AUTH="${TWILIO_ACCOUNT_SID}:${TWILIO_AUTH_TOKEN}"
DIR="$(cd "$(dirname "$0")" && pwd)"
TEMPLATES_DIR="$DIR/templates"
SIDS_FILE="$DIR/content-sids.env"

: > "$SIDS_FILE"
echo "# Generated by create-templates.sh on $(date -Iseconds)" >> "$SIDS_FILE"

for f in "$TEMPLATES_DIR"/*.json; do
  name=$(basename "$f" .json)
  echo "── Creating template: $name ──"

  resp=$(curl -sS -u "$AUTH" \
    -H "Content-Type: application/json" \
    -X POST "https://content.twilio.com/v1/Content" \
    --data-binary @"$f")

  sid=$(echo "$resp" | python3 -c "import sys, json; d = json.load(sys.stdin); print(d.get('sid', ''))")

  if [[ -z "$sid" || ! "$sid" == HX* ]]; then
    echo "  FAILED to create $name"
    echo "$resp" | python3 -m json.tool
    continue
  fi

  echo "  Created $sid"

  # Submit for WhatsApp/Meta approval. Category UTILITY for all customer-facing
  # notifications. team_dispatch goes to ops staff, so still UTILITY (internal
  # business operations notification).
  echo "  Submitting for Meta approval..."
  approval=$(curl -sS -u "$AUTH" \
    -H "Content-Type: application/json" \
    -X POST "https://content.twilio.com/v1/Content/${sid}/ApprovalRequests/whatsapp" \
    --data "{\"name\":\"${name}\",\"category\":\"UTILITY\"}")
  echo "$approval" | python3 -m json.tool || true

  # Write env var line for this template
  env_var="TWILIO_CONTENT_SID_$(echo "$name" | tr '[:lower:]' '[:upper:]')"
  echo "${env_var}=${sid}" >> "$SIDS_FILE"

  echo
done

echo "Done. Content SIDs written to: $SIDS_FILE"
echo "Copy these into prod .env.local and n8n environment."
